{
 "title": "Scheduler",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Scheduler Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sched_up" }
   ]
  },
  {
   "title": "Scheduler Bitcoin Value",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "sched_bitcoin" }
   ]
  },
  {
   "title": "Scheduler - User Random Value",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "sched_mycounter" }
   ]
  },
  {
   "title": "Scheduler Percentile Running Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "sched_run_total_elapsed_time" }
   ]
  },
  {
   "title": "Schedule Total Number Of Run",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "sched_runs" }
   ]
  }
 ]
}